version: '3.3'
services:

  #db:
   # image: postgres:13.0-alpine
    #volumes:
     # - /var/lib/postgresql/data/
    #env_file:
     # - ./.env # TODO включить перед продом

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    #volumes:
    #  - static_admin:/app/static/
    env_file:
      - ./.env
    #depends_on:
    #  - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

    depends_on:
      - backend
