# Generated by Django 2.2.16 on 2022-10-04 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221004_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='test',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть менее минуты.')], verbose_name='Время приготовления (в минутах)'),
            preserve_default=False,
        ),
    ]
