# Generated by Django 2.2.16 on 2022-10-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20221004_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='test',
        ),
    ]
